name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          xcodebuild test -scheme Tests -project 'SwiftUI Navigation/SwiftUI Navigation.xcodeproj' -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' -resultBundlePath TestsResult.xcresult build test | xcpretty && exit ${PIPESTATUS[0]}
      - uses: kishikawakatsumi/xcresulttool@v1
        if: success() || failure()
        with:
          path: TestsResult.xcresult
          token: ${{ secrets.REPO_TOKEN }}
      - name: Archive failed snapshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: 'SwiftUI Navigation/failed-snapshots'
