name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          xcodebuild test -scheme Tests -project 'SwiftUI Navigation/SwiftUI Navigation.xcodeproj' -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' build test
